// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd27F-jNb1H0PY6sXz3gGpnELMq5jUCxo',
    appId: '1:407132101706:web:ab7b2e4b13f72f9c78dab3',
    messagingSenderId: '407132101706',
    projectId: 'workouts-v3-7bf58',
    authDomain: 'workouts-v3-7bf58.firebaseapp.com',
    storageBucket: 'workouts-v3-7bf58.appspot.com',
    measurementId: 'G-4QSWGWRBVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdV4SDA4PSJgUTr88zmwGs2ItlixRXw5Y',
    appId: '1:407132101706:android:39b656eb6e5ff2f178dab3',
    messagingSenderId: '407132101706',
    projectId: 'workouts-v3-7bf58',
    storageBucket: 'workouts-v3-7bf58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFqMaeYhacQrrrHnIspPd_fg8dsYe0X0c',
    appId: '1:407132101706:ios:bfac5b883afc318878dab3',
    messagingSenderId: '407132101706',
    projectId: 'workouts-v3-7bf58',
    storageBucket: 'workouts-v3-7bf58.appspot.com',
    iosBundleId: 'com.example.workoutsV3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFqMaeYhacQrrrHnIspPd_fg8dsYe0X0c',
    appId: '1:407132101706:ios:36ee5c361c924bb378dab3',
    messagingSenderId: '407132101706',
    projectId: 'workouts-v3-7bf58',
    storageBucket: 'workouts-v3-7bf58.appspot.com',
    iosBundleId: 'com.example.workoutsV3.RunnerTests',
  );
}
