// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALLDDmCMdRyDVp4ZTWNdvFVTFcaWA-zCI',
    appId: '1:66066305844:web:92a960f7732f42b9c98b61',
    messagingSenderId: '66066305844',
    projectId: 'workouts-v3',
    authDomain: 'workouts-v3.firebaseapp.com',
    storageBucket: 'workouts-v3.appspot.com',
    measurementId: 'G-R8E7Z211LC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgZceYo4sAo6p8CpW-wcNBEXUydueojo8',
    appId: '1:66066305844:android:afac192b06fa41c4c98b61',
    messagingSenderId: '66066305844',
    projectId: 'workouts-v3',
    storageBucket: 'workouts-v3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLZGp4Qta5Zr8F89hTR2eCIo862WbUoPw',
    appId: '1:66066305844:ios:46f47032dd190247c98b61',
    messagingSenderId: '66066305844',
    projectId: 'workouts-v3',
    storageBucket: 'workouts-v3.appspot.com',
    iosClientId:
        '66066305844-kmobk4uui9q6jandu4fn0pj0apqkeh5m.apps.googleusercontent.com',
    iosBundleId: 'com.example.workoutsV3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLZGp4Qta5Zr8F89hTR2eCIo862WbUoPw',
    appId: '1:66066305844:ios:e02da6c0e86de97ac98b61',
    messagingSenderId: '66066305844',
    projectId: 'workouts-v3',
    storageBucket: 'workouts-v3.appspot.com',
    iosClientId:
        '66066305844-849rf7a02trhv091h903sapbqdgutl9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.workoutsV3.RunnerTests',
  );
}
